### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by Daqu** [Crystal-SDS/INSTALLATION#1]
this is my installation log→[crystal_aio_installation.log](https://pastebin.com/RW9Apjvh)
hava u ever try to deploy Crystal via docker?when i tried to deploy crystal via VM,i found it maybe out of date

**Comment by JosepSampe** [comment]
Hi @Daqu, there was an issue updating pip package in the script. It is resolved with the last commit. Thanks for reporting.
